spring:
  application:
    name: app

  datasource:
    url: jdbc:postgresql://localhost:5432/springtestdb
    username: postgres
    password: Danone0502603734!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
